# 📝메모\_231223

## 🔎 현재 학습 플랜

- 책 훑고, MDN 보면서 PPT 만들기

| 순서 | 일정  | 내용         | 관련 서적/강의              |
| ---- | ----- | ------------ | --------------------------- |
| 1    | 45~47 | JS 개념 공부 | 모던 자바스크립트 Deep Dive |

---

# 45. Promise

## 비동기 함수

- 비동기 함수를 호출하면, 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료

```tsx
function foo() {
  console.log(1);
  // 비동기 작업
  setTimeout(() => {
    g = 100;
  }, 0);
  console.log(2);
}
```

- 비동기 함수 내부의 비동기도 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
- 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나, 상위 스코프의 변수에 할당했을 때 기대한 대로 동작 x

```tsx
let g = 0;
setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

### 이벤트 핸들러의 실행은?

- 이벤트가 발생 시, 이벤트의 프로퍼티에 바인딩된 이벤트 핸들러가 즉시 실행되지 않는다.
- (xhr.onload) 서버로부터 응답이 도착하면(load 이벤트가 발생하면) `태스크 큐`에 저장되어 대기 => 콜 스택이 비면 이벤트 루프에 의해 `콜 스택`으로 푸시되어 실행된다. => 함수이므로 평가-실행 컨텍스트 생성-콜 스택 푸시-실행 과정을 거침

### 에러 캐치 못하는 이유?

```tsx
try {
  setTimeout(() => throw new Error('NO'), 1000);
} catch (e) {
  console.error(e.message); // x
}
```

- setTimeout 호출, setTimeout 실행 컨텍스트 생성 -> 콜 스택에 push -> 실행, 종료 (비동기니까 콜백을 기다리지 않음) / **setTimeout에 전달된 콜백 함수(() => throw new Error('NO'))가 타이머에 등록** -> 콜 스택에서 pop -> 타이머가 만료되면 콜백이 태스크 큐로 push -> 대기 -> (콜 스택이 비었을 때) 콜백 함수에 의해 콜 스택으로 push -> 평가, 실행 컨텍스트 생성, 콜스택 푸시, 실행, 종료
- 콜백 함수가 실행될 때, setTimeout은 콜 스택에 없음
  => 콜백 함수를 호출한 것이 setTimeout이 아니다!
  - 그럼 누구냐? 전역이다 => 전역 오류
- 에러는 호출 스택(call stack)을 따라 호출자(caller) 방향으로 전파

## Promise

- `빌트인 객체`
- new 연산자와 함께 호출 => Promise 객체를 생성
- 인수: resolve, reject
- 상태: pending(비동기 수행 전/기본), fulfilled(수행 성공/resolve), rejected(수행 실패/reject)
  - pending과 settled 상태

```tsx
const myPromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("foo");
  }, 300);
});
```

- 👉 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체

## Promise chaining methods

- `Promise.prototype.then`: 언제나 promise 반환 / 암묵적으로 반환값을 resolve, reject
- `Promise.prototype.catch`: 메서드의 콜백함수는 프로미스가 rejected 상태인 경우에만 호출, 언제나 promise 반환
- `Promise.prototype.finally`: 메서드의 콜백함수는 resolve, reject와 상관없이 무조건 한 번 실행

### Promise catch 작동

- 내부적으로 then(undefined, onRejected)을 호출한다.

```tsx
const wrongUrl = `https://wrongurl.com`;
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .then(undefined, (err) => console.log(err)); // Error: 404
```

### Promise static method

- Promise.resolve / Promise.reject
  - 존재하는 값을 래핑하여 프로미스를 만든다.

```tsx
const successValue = { success: "nice" };
Promise.resolve(successValue);
```

- Promise.all
  - 인수: 프로미스s 이터러블 (이터러블 요소가 프로미스가 아닌 경우, resolve를 통해 프로미스로 래핑)
  - 배열 순서 보장
  - 하나라도 rejected되면 나머지 프로미스 fulfilled를 기다리지 않고 즉시 종료
- https://api.github.com/users/dusunax 이거 뭐임!?
- Promise.race
  - 인수: 프로미스s 이터러블
  - 가장 먼저 fulfilled된 프로미스의 처리 결과를 resove하는 프로미스를 반환
  - 하나라도 rejected되면 나머지 프로미스 fulfilled를 기다리지 않고 즉시 종료
- [ES11] Promise.allSettled
  - 인수: 프로미스s 이터러블
  - 모든 프로미스의 처리 결과가 담겨있다
  - rejected => {status: 'rejected', reason: Error: Error! at <~~>}

## 마이크로태스크 큐 microtask queue

- 프로미스의 후속 처리 메서드의 콜백 함수는 마이크로태스크 큐에 저장
- 이벤트루프는 microtask queue가 비면 task queue의 대기 함수를 가져감

```tsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));

// 2
// 3
// 1
```

## fetch

- `클라이언트 사이드 Web API`
- XMLHttpRequest 보다 사용법이 간단하고, 프로미스를 지원한다
- HTTP Response 객체를 래핑한 Promise 객체 반환
- 에러 핸들링
  - 에러 시 ok 상태가 false인 Response 객체를 resolve
  - 네트워크 장애, CORS 시, Promise reject

```tsx
const wrongUrl = `https://wrongurl.com`;
fetch(wrongUrl)
  .then((res) => {
    if (!res.ok) throw new Error(res.statusText);
    return res.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.log(err));
```

# 제너레이터 Generator와 async/await

## Generator

- [ES6] 코드 실행을 일시 중지했다가 필요한 시점에 재개
- 함수 호출자에게 제어권을 yield => 함수 상태를 주고 받을 수 있다
- 실행 시, 이터러블이면서 이터레이터인 제너레이터 객체를 반환

### 정의

- `function*`로 선언, 하나 이상의 yield 표현식을 포함
- 화살표x, new 키워드와 생성자x

```tsx
function* genDecFunc() {
  yield 1;
}

const obj = {
  *genObjMethod() {
    yield 1;
  },
};
```

### Generator Object

- Generator 객체
- 메서드
  - next():
    - `value`, `done: false` 프로퍼티를 가진 객체를 반환, Iterator Result Object
    - yield 앞까지 진행 / 더 없으면 마지막까지 진행하고 `done: true`
  - return():
    - `value`, `done: true`

## async/await

- [ES8] 프로미스 기반 동작 = Promise 객체 반환
- await은 promise settled까지 다음 실행 대기

```tsx
let attempt = 3;
let success = false;

while (attempt > 0 && !success) {
  try {
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // api call

    success = true;
    attempt = 0;
  } catch (error) {
    console.log(`attempt: ${attempt}`, error);
  } finally {
    attempt--;
  }
}

if (success) {
  console.log("good");
} else {
  console.log("bad");
}
```

- 병렬 처리

```tsx
async function foo() {
  const res = await Promise.all([
    new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // ~~/todo/1
    new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // ~~/todo/2
    new Promise((resolve) => setTimeout(() => resolve(3), 1000)), // ~~/todo/3
  ]);
  console.log(res); // [1, 2, 3]
}

foo(); // 약 3초
```

- 비동기 처리 결과를 가지고 비동기 처리

```tsx
async function bar(n) {
  const a = await new Promise((resolve) => setTimeout(() => resolve(1), 3000));
  const b = await new Promise((resolve) =>
    setTimeout(() => resolve(a + 1), 2000)
  );
  const c = await new Promise((resolve) =>
    setTimeout(() => resolve(b + 1), 1000)
  );

  console.log([a, b, c]); // [1, 2, 3]
}

bar(); // 약 6초
```

- 콜백 함수를 인수로 전달받는 비동기 함수와 달리, `프로미스를 반환`하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자 caller 가 명확하다 => 에러가 발생했을 때 전파를 캐치할 수 있다.
- 프로미스를 사용하는 이유 > 에러 핸들링 (caller가 명확하므로 에러 캐치 가능)
- catch문 안쓰면? 에러를 reject하는 promise 반환

---

### 예제 재료

- 깃헙 api `https://api.github.com/users/`를 사용해서 스터디원 이름 뽑기
- 프로미스 체이닝
